# Generated by Django 3.2.5 on 2021-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
    ]
